### ISSUE TITLE
Does not show python virtual env prompt

### ISSUE THREAD

**Issue by bkhouri** [bluz71/bash-seafly-prompt#2]
python allows the creation of virtual environments, which is essentially a self-contains python installation.  When "activating" a python virtual environment (venv), the venv prompt is displayed on the bash prompt by default.

for example, if my bash prompt is `user ~/present/working/directory $` then activating the virtual environment would generate a prompt of `(<venv prompt>) user ~/present/working/directory $`

When using seafly bash prompt, the venv prompt is not displayed on the console's prompt

Here's a screen recording showing the issue.

![screen_recording](https://user-images.githubusercontent.com/10914661/50975541-debed900-14bb-11e9-92f5-24f9df073197.gif)

Notice that after running `source ~/venv3/bin/python`, the prompt is prefixed with `(venv3)`.

**Comment by bluz71** [comment]
Ok, tricky issue.

I have come up with an initial solution, but not yet documented since I would like your feedback, it may not be the desired solution.

A new environment variable now exists that allows a user to specify their own prefix segment. That variable will be `eval`'d in Bash. So one puts their own desired shell code into that environment variable.

In your case I think it could be something like:

```sh
SEAFLY_PROMPT_PREFIX='basename "$VIRTUAL_ENV"'
```

**Comment by bkhouri** [comment]
Personally, I would rather the prompt update automatically, similar to the default.  When I "activate" a python virtual environment, the prompt is automatically updated to show the virtual environment name (which is automatically retrieved by bash).  And when I `deactivate`, the prompt is updated to not display the virtual environment prefix.

This fact that seafly doesn't display the virtual environment prompt might be related to the fact that sourcing `command_prompt.bash` sets the `PROMPT_COMMAND` variable.

**Comment by bluz71** [comment]
The Python *virtual environment* script directly overwrites `PS1`. 

The seafly prompt sets `PROMPT_COMMAND` to a function which itself sets `PS1`. Basically, whatever the *virtual environment* does to the prompt will have no effect since that function assume people are not overwriting `PROMPT_COMMAND`.

Basically, with the hook provided (via the undocumented `SEAFLY_PROMPT_PREFIX`) you will need to codify the python virtual env yourself.

I do a little bit of Ruby programming on the side, so I could image someone wanting the current Ruby version in the prompt, but only when inside a Ruby project (signified via the presence of a `Gemfile`).

That can be accomplished via this:

```sh
SEAFLY_PROMPT_PREFIX="if [[ -f ./Gemfile ]]; then echo $(chruby | grep '*' | cut -d' ' -f3); fi"
```

If a `Gemfile` exists, then use `chruby` to print the current Ruby version (via `grep` and `cut`).

In your case I believe the presence or absence of the `VIRTUAL_ENV` environment variable signifies an activated or deactivated Python virtual environment (I think). If so, you could do:

```sh
SEAFLY_PROMPT_PREFIX="if [[ -z $VIRTUAL_END ]; then echo '(venv)'; fi"
```

There is no way to make the virtual environment work in a simple way like before since seafly completely takes over the prompt command, it has to for it to do all of the Git stuff each time the prompt is recomputed.

I can't think of any other way to do what you want. I still believe you can use `SEAFLY_PROMPT_PREFIX` to achieve what you want, with a little shell scripting. Use my examples above as a starting point.

**Comment by bkhouri** [comment]
Ah, yes.. here's what worked for me

```
SEAFLY_PROMPT_PREFIX='if [ -n "${VIRTUAL_ENV}" ]; then echo "($(basename ${VIRTUAL_ENV}))"; fi'
```

**Comment by bkhouri** [comment]
would it be possible to add an option to customize it's colour too?

**Comment by bluz71** [comment]
The `SEAFLY_PROMPT_PREFIX` color is now configurable via the new `SEAFLY_PREFIX_COLOR` variable.

The new *prefix* functionality should now cover must misc user needs such as: display Ruby version, or display Python virtual environment, or display Docker details etc etc.
