### ISSUE TITLE
Add NVM support?

### ISSUE THREAD

**Issue by niderhoff** [bluz71/bash-seafly-prompt#6]
Nothing to add here, I just love it. Thank you. With all the zsh and fish fancy prompts running around. As a die-hard bash-er I am just happy my prompt can get some love too :)

Feel free to close this, just wanted to say thank you.

p.s. also I love your vim color scheme!

**Comment by niderhoff** [comment]
I also added a little feature request so this issue is not just off-topic spam.

What about supporting NVM? (maybe we can create a prompt-prefix example for showing the active node version in the Readme).

**Comment by bluz71** [comment]
> Nothing to add here, I just love it. Thank you. With all the zsh and fish fancy prompts running around. As a die-hard bash-er I am just happy my prompt can get some love too :)
> 
> Feel free to close this, just wanted to say thank you.

I appreciate that. Hopefully this prompt adds a little bling to your Bash life :ok_hand:

**Comment by bluz71** [comment]
> What about supporting NVM? (maybe we can create a prompt-prefix example for showing the active node version in the Readme).

I have added an example for the Node Version Manager:

```sh
SEAFLY_PROMPT_PREFIX='echo "($(nvm current))"'
```

However, I do recommend [fnm](https://github.com/Schniz/fnm) instead of [nvm](https://github.com/nvm-sh/nvm) due to its superior startup performance. If using *fnm* then the prompt command would be `fnm current` instead of `nvm current`. Up to you.

Cheers.
